name: design_system_demo
description: "Sketch Design System showcase app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  core:
    path: ../../packages/core
  design_system:
    path: ../../packages/design_system
  qna:
    path: ../../packages/qna
  notice:
    path: ../../packages/notice
  dio: ^5.4.0
  flutter_dotenv: ^5.2.1
  lucide_icons_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
  fonts:
    - family: Loranthus
      fonts:
        - asset: assets/fonts/Loranthus.ttf
    - family: KyoboHandwriting2019
      fonts:
        - asset: assets/fonts/KyoboHandwriting2019.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
