name: my_monorepo
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dev_dependencies:
  melos: ^6.0.0  # 또는 최신

melos:
  workspace:
    - apps/mobile/**
    - packages/shared/**
